### PR TITLE
Api2 fix

### PR DESCRIPTION
**Pull request by nstiurca**
Make api2 slightly more lenient with the input types: accepts any `Number` instead of `Csizet`, and any `Real` instead of `CL_float` and `CL_double`. Also cleaner handling of enums.

### CODE REVIEW

**Comment by jakebolewski** [comment]
It's much easier to have a strict (macro) generated definition and then wrap that in a higher level API, so I see @dfdx point.

**Comment by dfdx** [comment]
@nstiurca Please, take a look at #15 . Does it cover your needs for `GEMM`?

Also, I think it's a good idea to alias `CL_float2` to `Complex64` and `CL_double2` to `Complex128`. They are not exactly the same types, but seem to be used like this anyway. In #15 I use `convert` for casting between types, but aliasing looks like a cleaner approach, so having it as a separate PR would be nice.

**Comment by nstiurca** [comment]
PR #15 looks delicious, can't wait to try it.

Regarding`CL_float2` etc, can you just cherry-pick c920a81 ? Or does it need more work to integrate well with new high level API?

**Comment by dfdx** [comment]
Basically, I wanted to highlight this specific change since somebody may have objections. So I created #16. 

BTW, #15 is now in master.

**Pull request closed without merging**
