### PR TITLE
cl.release! was deprecated in OpenCL.jl PR 80

### PR DESCRIPTION
**Pull request by nstiurca**
needed because of https://github.com/JuliaGPU/OpenCL.jl/pull/80

### CODE REVIEW

**Comment by dfdx** [comment]
Does it make sense to name this updated function `finalize` too? For backward compatibility we can make an alias as well.

**Comment by nstiurca** [comment]
Maybe, but what about `function terminate()`? Should we refactor that to use Julia's `finalizer` mechanisms?

Actually--taking this idea to its logical conclusion--it occurs to me that this function might be entirely superfluous. After all, since `queue` and `context` have been registered with `finalizer`, then `compute_context_holder` vector should automagically trigger the `finalize` calls, printing any problems, but otherwise swallowing the errors, just as the implementation of `release!` does. Then `teardown()` could just do something like `map(compute_context_holder) do cch map(finalize, cch) done` if we really want to finalize those objects now, or not and wait for the garbage collector to take care of it whenever.

**Comment by dfdx** [comment]
Using Julia's built-in finalizers sounds like a great idea! 

More generally, I believe it's time to think about cleaning up and creating stable API. Currently this package contains some old code for which I don't really understand the purpose, no tests and almost no documentation. It's hard to talk about package maturity without all these things.

**Comment by dfdx** [comment]
@nstiurca Since this branch had conflicts with latest master and I don't have permissions to push to your repository, I moved your commit to #20. 

I'm going to merge #20 now as is, please, feel free to introduce `finalizer()` changes we've discussed in an additional PR.

**Pull request closed without merging**
