### PR TITLE
"clblas" -> "homebrew/science/clblas"

### PR DESCRIPTION
**Pull request by dlfivefifty**
Fixes brew name

### CODE REVIEW

**Comment by musm** [comment]
Does this not require `@osx Homebrew` in the REQUIRE file?

**Comment by dlfivefifty** [comment]
That's more a comment about the branch sd/osx then this pull request, but I can fix it

**Comment by dlfivefifty** [comment]
REQUIRE file already has `@osx Homebrew`.   Note that this pull request is in to the sd/osx branch, not the main branch

**Comment by musm** [comment]
ah... ignore my comment then

**Comment by dfdx** [comment]
Travis isn't happy because CI isn't configured to work with OpenCL-enabled devices, but it's a separate issue. Do tests pass on your machine?

**Comment by dlfivefifty** [comment]
No, but due to https://github.com/JuliaGPU/CLBLAS.jl/issues/32

**Comment by SimonDanisch** [comment]
I guess we can merge this then and figure out #32 separately!

**Comment by dfdx** [comment]
This doesn't make much sense if MacOS version eventually doesn't work, but I agree that it also doesn't hurt if we have it merged.

**Pull request merged**
